# Generated by Django 4.2.11 on 2025-06-05 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="report",
            name="description",
            field=models.TextField(verbose_name="Description"),
        ),
    ]
